
services:
  r3:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net4:
        ipv4_address: 10.0.4.2

networks:
  net4:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.4.0/24